```toml
name = "badminton-display"
main = "worker.js"
compatibility_date = "2026-09-17"

[assets]
directory = "./"
binding = "ASSETS"

[[kv_namespaces]]
binding = "BADMINTON_STATE"
id = "2d3475edfd16404ca757e2a9ab0d706c"
```
